# ==========================
# Configuracion de la practica TSP
# ==========================

# Ejecuciones aleatorias
numEjecuciones = 3

DNI = 61588823

ficherosDatos = ch130.tsp

ficherosMejores = _best.txt

# Algoritmos que se ejecutaran
ejecutarGRE = true
ejecutarGRA = false
ejecutarBL = false
ejecutarTA = false

# Parametros
kGRA = 5
maxEvaluacionesBL = 10000
tenenciaTabu = 10
maxIteracionesTA = 5000

rutaInstancias = src/resources/
rutaResultados = resultados/
rutaLogs = logs/